// <auto-generated />
using System;
using Danciu_Radu_Lab4_BAMI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Danciu_Radu_Lab4_BAMI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113160018_InitialPredictionHistory")]
    partial class InitialPredictionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Danciu_Radu_Lab4_BAMI.Models.PredictionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("PassengerCount")
                        .HasColumnType("real");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PredictedPrice")
                        .HasColumnType("real");

                    b.Property<float>("TripDistance")
                        .HasColumnType("real");

                    b.Property<float>("TripTimeInSecs")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PredictionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
